version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6579:6379"
    restart: on-failure
    container_name: redis-for-dotnet-webapi-with-mssql
  dotnet-webapi:
    image: "iammukeshm/dotnet-webapi:latest"
    environment:
      - "DatabaseSettings__ConnectionString=Server=db;Database=rootTenantDb;Use\
        r=sa;Password=securePassword123;MultipleActiveResultSets=true"
      - "DatabaseSettings__DBProvider=mssql"
      - "HangfireSettings__Storage__ConnectionString=Server=db;Database=rootTen\
        antDb;User=sa;Password=securePassword123;MultipleActiveResultSets=true"
      - "HangfireSettings__Storage__StorageProvider=mssql"
      - "CacheSettings__RedisURL=redis"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_URLS=https://+:5051;http://+:5061"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5051:5051"
      - "5061:5061"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    container_name: dotnet-webapi-with-mssql
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=securePassword123"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q
        "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
